### PR TITLE
Fix #174: defer preparing of history options.

### LINKED ISSUE #174: Calling `track_history on: :fields` requires `track_history` be executed after all field/relations are defined
```
      context 'when tracking all fields' do
        context 'when field is added after track_history' do
          before :all do
            SpecModel = Class.new do
              include Mongoid::Document
              include Mongoid::History::Trackable
              track_history on: :fields
              field :foo
            end
          end

          it { expect(SpecModel.tracked?(:foo)).to be true }

          after :all do
            Object.send(:remove_const, :SpecModel)
          end
        end
      end
```

=>

```
     Failure/Error: it { expect(SpecModel.tracked?(:foo)).to be true }

       expected true
            got false
```

This is because `track_history` parses and memoizes the list of fields and relations at the moment of execution.  Is this expected behavior?  Easy fix is to allow `Attribute` classes to reparse the `on` option when preparing attributes.

### PR DESCRIPTION
**Pull request by dblock**
Replaces https://github.com/mongoid/mongoid-history/pull/204

### CODE REVIEW

File: lib/mongoid/history/trackable.rb [hunk 1]
```diff
@@ -494,7 +493,7 @@ def trackable_scope
         end
 
         def history_trackable_options
-          @history_trackable_options ||= Mongoid::History.trackable_class_options[trackable_scope]
+          @history_trackable_options ||= Mongoid::History.trackable_class_options[trackable_scope].prepared
```
Comment (mikwat) [inline lib/mongoid/history/trackable.rb]: Nice 👍
